compatibility_date = "2023-03-09"
compatibility_flags = ["durable_object_alarms"]

name = "cloudly-analytics-administration"
workers_dev = true
routes = []
vars = { }
main = "./dist/_worker.js"


kv_namespaces = [
	{ binding = "listenerConfigurationStorage", id = "caa14ee7713348029984fd1a297b6842", preview_id = "4793f1258dd5459f86d814ab5e0658bf"}
]

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules" # Miniflare needs this

[durable_objects]
bindings = [
	{ name = "bufferStorage", class_name = "BufferStorage" },
	{ name = "bucketStorage", class_name = "BucketStorage" },
]

[[migrations]]
tag = "v2023-03-07"
new_classes = ["BufferStorage", "BucketStorage"]


[env.production]
workers_dev = false
vars = {  }
#durable_objects.bindings = []
#kv_namespaces = []
r2_buckets = []

[env.local]
workers_dev = true
vars = { adminSecret = "adminSecret", bigQueryPrivateKey = '{"type":"service_account"...}' }
#durable_objects.bindings = []
#kv_namespaces = []
r2_buckets = []

[miniflare]
durable_objects_persist = "./.miniflare/durable-objects/"
kv_persist = "./.miniflare/kv/"
port = 8788

