compatibility_date = "2022-11-25"
compatibility_flags = ["durable_object_alarms"]

name = "cloudly-analytics-storage"
workers_dev = true
routes = []
vars = { }
main = "./dist/_worker.js"


kv_namespaces = [
	{ binding = "listenerConfigurationStorage", id = "caa14ee7713348029984fd1a297b6842", preview_id = "4793f1258dd5459f86d814ab5e0658bf"}
]

[build]
command = "npm install && npm run build"


[durable_objects]
bindings = [
	{ name = "eventStorage", class_name = "EventStorage" },
	{ name = "bucketStorage", class_name = "BucketStorage" },
]

[[migrations]]
tag = "v2023-03-07"
new_classes = ["EventStorage", "BucketStorage"]

[env.production]
workers_dev = false
vars = {  }
#durable_objects.bindings = []
#kv_namespaces = []
r2_buckets = []

[env.local]
workers_dev = true
vars = { adminSecret = "adminSecret" }
#durable_objects.bindings = []
#kv_namespaces = []
r2_buckets = []

[miniflare]
durable_objects_persist = "./.miniflare/durable-objects/"
kv_persist = "./.miniflare/kv/"
port = 8788
