name: "Bump"

on:
  push:
    branches:
      - "master"
jobs:
  bump-version:
    name: "Bump Version"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci: version bump')"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: "Setup Node"
        uses: "actions/setup-node@v3"
        with:
          node-version: current
          cache: "npm"
      - name: "Version Bump"
        id: version-bump
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          git config --global user.name "lerna version"
          git config --global user.email lerna@example.com
          npx lerna version patch --yes --message="ci: version bump"
